### ISSUE TITLE
[Gentoo compilation] vulkan/vk_layer_dispatch_table.h not found, with vulkan >=1.3.246 (Solved)

### ISSUE THREAD

**Issue by jaypeche** [felixdoerre/primus_vk#91]
Since vulkan >=1.3.246, primus_vk compilation returns :

`primus_vk.cpp:7:10: fatal error: vulkan/vk_layer_dispatch_table.h: No such file or directory`

Compilation logs [here](https://gist.github.com/jaypeche/fa09b8855a81f09a6ede74f1239286e2)

Header files on /usr/include/vulkan : https://gist.github.com/jaypeche/d43ea291db15d701afcdb516f9da3a65 

What's vulkan header needed to compile primus_vk-1.6.2 before vulkan upgrade ?

Thx in advance

**Comment by jaypeche** [comment]
Header was moved to /usr/include/vulkan/generated
Modify header path solve this issue.
Fix patch [here](https://ftp.pingwho.org/pub/gentoo/ftp/overlay/dbox2-overlay/x11-libs/primus_vk/files/primus_vk_gentoo_header_fix.diff)

**Comment by felixdoerre** [comment]
I've tracked it down to this change in the vulkan SDK: https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/ca01a6ef1bb49eb05a99607f69ac7771648780fe

Personally I would favor adding `-I/usr/include/vulkan/generated` to the makefile here `https://github.com/felixdoerre/primus_vk/blob/master/Makefile#L19` (and two lines below), so we stay compatible with both versions.

I've adjusted this on master, you can try if that builds for you.

**Comment by jaypeche** [comment]
This solution is really better for portability !

* primus_vk compile fine with primus_vk-1.6.2 (tag v1.6.2) and primus_vk-9999 (master branch)...
I've upgraded [new revision](https://ftp.pingwho.org/pub/gentoo/ftp/overlay/dbox2-overlay/x11-libs/primus_vk/) of ebuild and applied your patch with success !

Thx

**Comment by jaypeche** [comment]
{Primus_vk 1.6.3 version bump Gentoo update 28 Jul 2023 at https://ftp.gentoo/ftp/overlay/dbox2-overlay/x11-libs/primus_vk/ChangeLog
